import {
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  AtSign,
  Award,
  BadgeCheck,
  BookMarked,
  BookOpen,
  BookOpenText,
  Briefcase,
  Calendar,
  Camera,
  ChevronDown,
  ChevronUp,
  Clapperboard,
  Clock,
  Crown,
  Droplets,
  ExternalLink,
  FileText,
  FlaskConical,
  Globe,
  GraduationCap,
  Handshake,
  ImageIcon,
  Leaf,
  Library,
  LineChart,
  Mail,
  Megaphone,
  Menu,
  Mic,
  MonitorPlay,
  Palette,
  Scale,
  ScrollText,
  Search,
  Star,
  Trophy,
  X,
  Zap,
  type LucideIcon,
} from "lucide-react";

const icons: Record<string, LucideIcon> = {
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-up-right": ArrowUpRight,
  "at-sign": AtSign,
  award: Award,
  "badge-check": BadgeCheck,
  "book-marked": BookMarked,
  "book-open": BookOpen,
  "book-open-text": BookOpenText,
  briefcase: Briefcase,
  calendar: Calendar,
  camera: Camera,
  "chevron-down": ChevronDown,
  "chevron-up": ChevronUp,
  clapperboard: Clapperboard,
  clock: Clock,
  crown: Crown,
  droplets: Droplets,
  "external-link": ExternalLink,
  "file-text": FileText,
  "flask-conical": FlaskConical,
  globe: Globe,
  "graduation-cap": GraduationCap,
  handshake: Handshake,
  image: ImageIcon,
  leaf: Leaf,
  library: Library,
  "line-chart": LineChart,
  mail: Mail,
  megaphone: Megaphone,
  menu: Menu,
  mic: Mic,
  "monitor-play": MonitorPlay,
  palette: Palette,
  scale: Scale,
  "scroll-text": ScrollText,
  search: Search,
  star: Star,
  trophy: Trophy,
  x: X,
  zap: Zap,
};

export default function Icon({
  name,
  size = 18,
  className,
  style,
}: {
  name: string;
  size?: number;
  className?: string;
  style?: React.CSSProperties;
}) {
  const IconComponent = icons[name];
  if (!IconComponent) return null;
  return <IconComponent size={size} className={className} style={style} />;
}
